kitware-resonant/cookiecutter-resonant

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/settings.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/apps.py
Without this, Django creates its own default AppConfig for the app.
> Load AppConfig subclass

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/tests/conftest.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/tests/factories.py
This removes the use of pytest_factorboy's @factory decorator as a matter of policy, as it's too fragile. Factories must be explicitly imported (if they are defined elsewhere) and registered in conftest.py.
The register function / decorator works by defining a new fixture function into the local Python file namespace. Pytest only automatically detects and registers global fixtures if they are within the namespace of conftest.py; fixtures defined as part of an import of other files are not registered.
> Make test factory registration less fragile

- README.md
- {{ cookiecutter.project_slug }}/README.md
- {{ cookiecutter.project_slug }}/setup.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/settings.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/urls.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/migrations/0001_initial.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/models/image.py
The default `Image` model now uses an `S3FileField` to store the file.
The `README.md` is still missing one step, creating the `django-storage`
bucket in the Minio instance. This needs to be either added to the set
up instructions (which would be a rather obnoxious step during initial
setup) or the `girder/minio-nonroot` image should include that bucket by
default.
> Add s3-file-field

- {{ cookiecutter.project_slug }}/setup.py
The major release of Celery introduced several breakages which have not yet been fixed upstream.
> Pin Celery to < 5

- {{ cookiecutter.project_slug }}/docker-compose.yml
This provides additional tools for directly accessing RabbitMQ in development.
> Use the "management" tag of the RabbitMQ image in Docker Compose

- {{ cookiecutter.project_slug }}/Procfile
- {{ cookiecutter.project_slug }}/README.md
- {{ cookiecutter.project_slug }}/docker-compose.override.yml
- {{ cookiecutter.project_slug }}/setup.py
Awaiting upstream fixes:
* https://github.com/celery/celery/pull/6365
* https://github.com/celery/celery/issues/6366
> Unpin Celery and upgrade to v5

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/urls.py
Without this change, the swagger UI view is wonky, showing `v1` and `s3-upload` as top-level tags, rather than combining them into one schema.
> Move S3 upload endpoints under /v1

- {{ cookiecutter.project_slug }}/setup.py
This fixes breakage due to an upstream major release.
> Pin minio version to < 7

- {{ cookiecutter.project_slug }}/setup.py
This fixes an incompatibility with minio 7.
> Pin django-minio-storage>=0.3.10

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/urls.py
URL patterns should consistently have trailing slashes.
> Append / to end of redoc and swagger URLs

- {{ cookiecutter.project_slug }}/MANIFEST.in
- {{ cookiecutter.project_slug }}/setup.py
This is necessary to support non-development installs of the project.
> Include package data when installing the project

- {{ cookiecutter.project_slug }}/README.md
- {{ cookiecutter.project_slug }}/dev/export-env.sh
- {{ cookiecutter.project_slug }}/dev/source-native-env.sh
This provides several improvements:
* Support for ZSH
* Support for empty lines in the .env file
* Support for comments in the .env file
* Allows a different .env file to be passed as an argument
* Cleans up internal shell variables
* Rename to `export-env.sh`, to clarify behavior and reflect the more general capabilities
Fixes #1
> Refactor the source-native-env.sh script

- README.md
- {{ cookiecutter.project_slug }}/tox.ini
I don't think most projects want to carry `pytest-custom-exit-code` as a long-term dependency. Rather than expect projects to remove the dependency and its CLI argument in the future, it's simpler to just give a (documented) single line of code to uncomment.
> Use a simpler approach to prevent pytest errors with no example_models

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/tasks.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/views.py
* Without example_code, exclude imports from `views.py`
* These are too specific to be consistently generally useful.
* Comment out unused sample import, instead of `noqa`-ing it.
* Downstreams may be scared to remove the `noqa` comment, but it should be obvious to uncomment the line.
> Remove noqa: F401 from minimal install

- {{ cookiecutter.project_slug }}/setup.py
- {{ cookiecutter.project_slug }}/tox.ini
This has the benefit of slimming down the production install slightly.
> Only install development requirements with the "dev" extra

- {{ cookiecutter.project_slug }}/setup.py
> Re-enable support for the old pip resolver

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/rest/image.py
`get_object` does permission checks, `get_object_or_404` does not.
> Use DRF get_object instead of get_object_or_404

- {{ cookiecutter.project_slug }}/docker-compose.yml
The RabbitMQ Docker image that the cookiecutter uses comes with the [RabbitMQ Management Plugin](https://www.rabbitmq.com/management.html) installed, but our docker-compose config doesn't expose the port for the browser interface.
> Expose port for RabbitMQ management console

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/urls.py
An explicit instance namespace is not necessary. From the Django docs:
> If the instance namespace is not specified,
> it will default to the included URLconf’s application namespace.
In Django OAuth Toolkit, the application namespace is already "oauth2_provider".
> Remove unnecessary namespace for Django OAuth Toolkit URLs

- {{ cookiecutter.project_slug }}/setup.py
`django-s3-file-field` has deprecated the `boto3` extra in favor of `s3`. https://github.com/kitware-resonant/django-s3-file-field/releases/tag/v1.0.0
As a result, a deprecation warning is logged when installing a project ejected from the cookiecutter
> Update S3FF extra name

- .github/workflows/ci.yml
- {{ cookiecutter.project_slug }}/.github/workflows/ci.yml
- {{ cookiecutter.project_slug }}/README.md
- {{ cookiecutter.project_slug }}/docker-compose.yml
* Remove remapping of Docker service ports
* This feature is not being used and adds too much complexity. When it was first requested, we assumed it would be more burdensome to start and stop projects, so running multiple projects in parallel was more beneficial.
* Use Alpine-based Docker images for services
* These images will not be extended, so the lack of tooling in Alpine is not an issue.
* Use the correct volume path for the "rabbitmq" Docker image
* This is taken from the Dockerfile of this image.
* Run the "postgres" Docker container with more memory
* This is recommended by the upstream readme.
> Update Docker usage

- django-resonant-settings/resonant_settings/oauth_toolkit.py
This is now the default upstream, as of django-oauth-toolkit 2.4.0.
> Remove explicit setting of "OAUTH2_PROVIDER.PKCE_REQUIRED"

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/settings/base.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/migrations/0002_initial_models.py
64-bit primary keys are probably excessive and may be introducing additional performance penalties.
This will require a more complicated migration to downstream: https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
> Don't use 64-bit primary keys

- {{ cookiecutter.project_slug }}/tox.ini
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/tests/conftest.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/tests/test_image.py
This package is fundamentally broken when creating non-trivial factories. Although it provides a slightly easier syntax for creating basic tests, it's likely to break in confusing ways as a project grows.
> Remove pytest-factoryboy

- django-resonant-settings/resonant_settings/celery.py
Celery logs a warning to the console if this setting is not explicitly configured.
> Explicitly set CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP

- .github/workflows/ci.yml
- django-resonant-settings/pyproject.toml
This allows downstream projects wishing to use an older Django to not be blocked by `django resonant-settings` refusing to install.
> Support Python >= 3.10 for django-resonant-settings

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/settings/testing.py
> Use a password hasher for tests that exists in the latest Django

- {{ cookiecutter.project_slug }}/pyproject.toml
- {{ cookiecutter.project_slug }}/tox.ini
This is recommended by Tox, will make it easier to install tooling into development environments, and perfectly fits the use case outlined by PEP 735.
> Declare development tools in dependency groups

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/settings/base.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/{{ cookiecutter.first_app_name }}/migrations/0002_initial_models.py
Reverts kitware-resonant/cookiecutter-resonant#274
The setting `DEFAULT_AUTO_FIELD` must be defined, or Django emits a warning.
> Revert "Don't use 64-bit primary keys"

- {{ cookiecutter.project_slug }}/dev/django.Dockerfile
Since this cookiecutter makes use of `pyproject.toml` instead of `setup.py`, the `dev/django.Dockerfile` fails when building, due to it referencing `setup.py` (which doesn't exist) instead of `pyproject.toml`.
> Copy pyproject.toml (instead of setup.py) during docker image build

- {{ cookiecutter.project_slug }}/dev/django.Dockerfile
This is allowed by the newer BuildKit capabilities of Docker. This results in a less fragile build process, as all the same files are available for both build and run.
> Mount the full source tree during Docker image build

- {{ cookiecutter.project_slug }}/dev/.env.docker-compose
- {{ cookiecutter.project_slug }}/pyproject.toml
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/settings/development.py
This is essential for the [`django.template.context_processors.debug` template context processor](https://docs.djangoproject.com/en/5.0/ref/templates/api/#django-template-context-processors-debug) to work when Django is running inside Docker. Otherwise, [`INTERNAL_IPS` really doesn't need to be set](https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-INTERNAL_IPS).
I'm not sure if anyone is even using the functionality from `django.template.context_processors.debug`, but I don't like that it's installed but would be broken when developing within Docker.
See https://github.com/django-commons/django-debug-toolbar/issues/1928 for more context.
> Add INTERNAL_IPS setting

- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/settings/development.py
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/settings/testing.py
This may lead to some slight configuration duplication, but may make it easier to understand where the correct place for settings should be.
This fixes a bug where the MinIO bucket name was not respected in development.
> Make development settings inherit directly from base, rather than testing

- {{ cookiecutter.project_slug }}/README.md
- {{ cookiecutter.project_slug }}/docker-compose.override.yml
- {{ cookiecutter.project_slug }}/pyproject.toml
- {{ cookiecutter.project_slug }}/{{ cookiecutter.pkg_name }}/settings/development.py
https://django-extensions.readthedocs.io/en/latest/runserver_plus.html
> Use runserver_plus as the development server

- django-resonant-settings/resonant_settings/production/s3_storage.py
The `total_seconds` method of a `timedelta` returns a float. This gets encoded in the presigned URL strings as`X-Amz-Expires=21600.0`, which AWS S3 rejects with the following message:
```xml
<Error>
<Code>AuthorizationQueryParametersError</Code>
<Message>X-Amz-Expires should be a number</Message>
<RequestId>ME54E3EF38K7PZKT</RequestId>
<HostId>Qz59L0WIiPX+p5bP3IZuCs7TLFigfaFzerZdo4WO63mGdUkP0ghQeLflDYvBIo7LtwJl8bd710M=</HostId>
</Error>
```
> Change AWS_QUERYSTRING_EXPIRE to integer type
